### ISSUE TITLE
Not working when called from client

### ISSUE THREAD

**Issue by bstocks** [ongoworks/meteor-speakingurl#2]
`getSlug(string)` returns `Uncaught TypeError: undefined is not a function` when run on the client. Works fine when run serverside. 

The speaking url js file appears to get loaded on the client but for some reason the function comes back undefined.

**Comment by aaronjudd** [comment]
@bstocks is this still an issue?

**Comment by bstocks** [comment]
Yes. I just tried it again and got the same error when running on the client.

**Comment by mquandalle** [comment]
Unless I miss something obvious, I believe it still doesn't work.

**Comment by aaronjudd** [comment]
I just tested `getSlug("test");` in the browser in my implementation, not sure what would be different.

**Comment by mquandalle** [comment]
I tested with a new meteor application and it works, so it's certainly something specific to my application.

**Comment by mquandalle** [comment]
Ok, I used `meteor update ongoworks:speakingurl` which doesn't seem to work even if it returns something saying "ongoworks:speakingurl  upgraded from 1.0.4 to 1.0.5". By manually upgrading (`@1.0.5 in `.meteor/package.js`) it works. Sorry for the false alarm.

**Comment by aaronjudd** [comment]
weird. *shrugs*
