### ISSUE TITLE
included in reaction:core

### ISSUE THREAD

**Issue by igreshev** [ongoworks/meteor-speakingurl#7]
I have a test reaction/meteor shop

IE9,IE10,IE11 can't open the page because auf Invalid character error in the compiled meteor javascript file. I tracked it down to this package. 

Chrome & Firefox everything is fine.

**Comment by igreshev** [comment]
with uglify-js: 2.4.17 works!

**Comment by jerefrer** [comment]
What exactly did you do to get rid of the error ?

I don't explicitly have uglifyjs in my packages, just meteor-speakingurl. Do I need to add uglifyjs to my app packages ? Then do I have to add some configuration somewhere ?

Thanks !
